<?xml version="1.0"?>
<robot name="dual_kuka_load" xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- ================= DEFINITIONS AND ARGS ================= -->
  
  <!-- Choose Object Type: 'bar', 'cube', 'sphere' -->
  <xacro:arg name="object_type" default="bar"/>
  
  <!-- Dimension Settings -->
  <!-- Bar: Length=1.0m, Width/Height=0.05m -->
  <xacro:property name="bar_length" value="1.0" />
  <xacro:property name="bar_thickness" value="0.05" />
  
  <!-- Cube: Side=0.2m -->
  <xacro:property name="cube_side" value="0.2" />
  
  <!-- Sphere: Diameter=0.2m -->
  <xacro:property name="sphere_dia" value="0.2" />

  <!-- Define Separation Distance based on Object Type -->
  <!-- Decouple Separation from Object Size -->
  <xacro:arg name="arm_gap" default="1.2"/>
  <xacro:property name="separation_dist" value="$(arg arm_gap)" />
  <xacro:property name="half_dist" value="${separation_dist/2}" />

  <!-- Include Macro -->
  <xacro:include filename="$(find arm_description)/urdf/dual_lbr_iiwa_14_r820_macro.xacro"/>

  <!-- World Link -->
  <link name="world"/>

  <!-- ================= ROBOT SPAWNING ================= -->

  <!-- Arm 1 at Origin -->
  <xacro:kuka_lbr_iiwa_14_r820 prefix="arm1_" parent="world" origin_xyz="0 0 0" origin_rpy="0 0 0" load_payload="false" load_gazebo_plugin="false"/>

  <!-- Arm 2 at X=separation_dist, Rotated 180 deg to face Arm 1 -->
  <xacro:kuka_lbr_iiwa_14_r820 prefix="arm2_" parent="world" origin_xyz="${separation_dist} 0 0" origin_rpy="0 0 ${pi}" load_payload="false" load_gazebo_plugin="false"/>

  <!-- ================= SHARED OBJECT ================= -->

  <link name="shared_block">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.00042" ixy="0" ixz="0" iyy="0.1202" iyz="0" izz="0.1202"/>
    </inertial>
    
    <visual>
      <geometry><box size="${separation_dist} ${bar_thickness} ${bar_thickness}"/></geometry>
      <material name="Red"><color rgba="1.0 0.0 0.0 1"/></material>
    </visual>
    
    <collision>
      <geometry><box size="${separation_dist} ${bar_thickness} ${bar_thickness}"/></geometry>
    </collision>
  </link>
  <gazebo reference="shared_block"><material>Gazebo/Red</material></gazebo>

  <joint name="arm1_to_block" type="fixed">
     <parent link="arm1_link_7"/>
     <child link="shared_block"/>
     <origin xyz="${half_dist} 0 0.15" rpy="0 0 0"/>
  </joint>

  <gazebo reference="arm1_to_block">
    <disableFixedJointLumping>true</disableFixedJointLumping>
    <preserveFixedJoint>true</preserveFixedJoint>
  </gazebo>

  <link name="arm2_flange_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="arm2_flange_joint" type="fixed">
    <parent link="arm2_link_7"/>
    <child link="arm2_flange_link"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
  </joint>

  <gazebo>
    <joint name="arm2_to_block_loop" type="fixed">
      <parent>arm2_flange_link</parent>
      <child>shared_block</child>
      <pose>${half_dist} 0 0 0 0 ${pi}</pose> 
    </joint>
  </gazebo>
  
  <!-- Global ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <gravity_compensation>false</gravity_compensation>
      <legacyModeNS>true</legacyModeNS> 
    </plugin>
  </gazebo>

</robot>